docker stop frontend
docker stop shipping
docker stop user
docker stop orders
docker stop carts
docker stop payment
docker stop catalogue
docker stop mongo-db
docker stop catalogue-db
docker stop nginx-proxy
docker stop nginx-static
docker stop session-db
docker stop frontend-backup1
docker stop frontend-backup2
docker stop frontend-backup3
docker stop frontend-backup4

docker rm frontend
docker rm shipping
docker rm user
docker rm orders
docker rm carts
docker rm payment
docker rm catalogue
docker rm mongo-db
docker rm catalogue-db
docker rm nginx-proxy
docker rm nginx-static
docker rm session-db
docker rm frontend-backup1
docker rm frontend-backup2
docker rm frontend-backup3
docker rm frontend-backup4
